name: Build & Deploy Codebase

on: 
  push:
    branches-ignore:
      - '**'
  pull_request:
    branches:
      - master
      - main
      - 'release/*'
 
jobs:
  branch-check:
    name: Branch Check
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.ref, 'refs/heads/feature/') }}
    steps:    
      - name: Get Branch Name
        run: |
          echo "This step will not run on 'feature/*' branches"          
          echo "branch_name=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
          echo "Branch name: $branch_name"
        id: extract_branch
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: [branch-check]
    defaults:
      run:
        working-directory: ./app/
    strategy:
      matrix:
        python-version: [3.11]
    env:
      MODE: "dev"
      PYTHON_VERSION: ${{ matrix.python-version }}
      TEST_SECRET: ${{ secrets.TEST_SECRET_NAME }}
      TEST_ENV_VAR_NAME: ${{ vars.TEST_ENV_VAR_NAME }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Echo Test
        run: |
          echo "Echo Test"
          echo  running ${{ vars.JOB_NAME }}
          
      - name: Install Dependencies
        run: |
          echo "Install Dependencies"
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt

      - name: Run Unit Test
        run: |
          echo "---Unit Test---"
          python -m unittest discover

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://dev.example.com
    needs: [unit-test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Dev
        run: |
          echo "Deploy to Dev"
          echo "Deploying to Dev"
          echo "Deployed to Dev"

  deploy-qa:
    name: Deploy to QA
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: qa
      url: https://qa.example.com
    needs: [unit-test, deploy-dev]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to QA
        run: |
          echo "Deploy to QA"
          echo "Deploying to QA"
          echo "Deployed to QA"

  deploy-uat:
    name: Deploy to UAT
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: uat
      url: https://uat.example.com
    needs: [unit-test, deploy-dev]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to UAT
        run: |
          echo "Deploy to UAT"
          echo "Deploying to UAT"
          echo "Deployed to UAT"

  deploy-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: 
      name: prod
      url: https://prod.example.com
    needs: [unit-test, deploy-dev, deploy-qa, deploy-uat]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Prod
        run: |
          echo "Deploy to Prod"
          echo "Deploying to Prod"
          echo "Deployed to Prod"