name: Build Codebase

on: 
  push:
    #branches-ignore: [release*]
    branches:
      - 'feature/*'
      - 'bugfix/*'
      - 'hotfix/*'
      - 'release/*'
      - 'main'
      - 'master'
  pull_request:
    branches: [master, main, 'release/*']
 
jobs:
  super-linter:
    name: Lint Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/
    strategy:
      matrix:
        python-version: [3.11]
    env:
      MODE: "dev"
      PYTHON_VERSION: ${{ matrix.python-version }}
      TEST_SECRET: ${{ secrets.TEST_SECRET_NAME }}
      TEST_ENV_VAR_NAME: ${{ vars.TEST_ENV_VAR_NAME }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Echo Test
        run: |
          echo "Echo Test"
          echo  running ${{ vars.JOB_NAME }}
          echo $TEST_SECRET
          echo $TEST_ENV_VAR_NAME
          echo ${{ secrets.TEST_SECRET_NAME }}
          echo ${{ vars.TEST_ENV_VAR_NAME }}
          echo "variable from shell environment : $TEST_ENV_VAR_NAME"
          
      - name: Install Dependencies
        run: |
          echo "Install Dependencies"
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt

      - name: Run Unit Test
        run: |
          echo "---Unit Test---"
          python -m unittest discover

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: [unit-test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Dev
        run: |
          echo "Deploy to Dev"
          echo "Deploying to Dev"
          echo "Deployed to Dev"

  deploy-qa:
    name: Deploy to QA
    runs-on: ubuntu-latest
    needs: [unit-test, deploy-dev]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to QA
        run: |
          echo "Deploy to QA"
          echo "Deploying to QA"
          echo "Deployed to QA"