name: Build & Deploy Codebase

on: 
  push:
    branches-ignore:
      - '**'
  pull_request:
    branches:
      - master
      - main
      - 'release/*'

env:
  SOME_VALUE: Hello World
  SOME_OTHER_VALUE: Hello World!!!
jobs:
  print-variables:
    name: Print Variables
    runs-on: ubuntu-latest
    steps:
      - name: Print Variables
        id: print_variables
        run: |
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_HEAD_SHA: $GITHUB_HEAD_SHA"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
          echo "GITHUB_ACTION: $GITHUB_ACTION"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
          echo "--------------------------------------"
          echo $SOME_VALUE
          echo $SOME_OTHER_VALUE
          branch_name=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} >> $GITHUB_OUTPUT
          echo "Branch name: $branch_name"
          echo "output_name=Helloooo" >> $GITHUB_OUTPUT
      - name: Get the output
        run: echo "The output was ${{ steps.print_variables.outputs.output_name }}"
      - name: Update environment variable
        run: |
          echo "SOME_OTHER_VALUE=New Value" >> $GITHUB_ENV
          echo $SOME_OTHER_VALUE
  branch-check:
    name: Branch Check
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.head_ref, 'feature/') }}
    steps:      
      - name: Extract branch name
        run: |        
          branch_name=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} >> $GITHUB_OUTPUT
          echo "Branch name: $branch_name"
        id: extract_branch_step
      - name: Get Branch Name
        run: |
          echo "This step will not run on 'feature/*' branches"
          echo "Branch name: ${{steps.extract_branch_step.outputs.branch_name}}"        
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: [branch-check]
    defaults:
      run:
        working-directory: ./app/
    strategy:
      matrix:
        python-version: [3.11]
    env:
      MODE: "dev"
      PYTHON_VERSION: ${{ matrix.python-version }}
      TEST_SECRET: ${{ secrets.TEST_SECRET_NAME }}
      TEST_ENV_VAR_NAME: ${{ vars.TEST_ENV_VAR_NAME }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Echo Test
        run: |
          echo "Echo Test"
          echo  running ${{ vars.JOB_NAME }}
          
      - name: Install Dependencies
        run: |
          echo "Install Dependencies"
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt

      - name: Run Unit Test
        run: |
          echo "---Unit Test---"
          python -m unittest discover

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://dev.example.com
    needs: [unit-test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Dev
        run: |
          echo "Deploy to Dev"
          echo "Deploying to Dev"
          echo "Deployed to Dev"

  deploy-qa:
    name: Deploy to QA
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: qa
      url: https://qa.example.com
    needs: [unit-test, deploy-dev]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to QA
        run: |
          echo "Deploy to QA"
          echo "Deploying to QA"
          echo "Deployed to QA"

  deploy-uat:
    name: Deploy to UAT
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: uat
      url: https://uat.example.com
    needs: [unit-test, deploy-dev]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to UAT
        run: |
          echo "Deploy to UAT"
          echo "Deploying to UAT"
          echo "Deployed to UAT"

  deploy-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: 
      name: prod
      url: https://prod.example.com
    needs: [unit-test, deploy-dev, deploy-qa, deploy-uat]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Prod
        run: |
          echo "Deploy to Prod"
          echo "Deploying to Prod"
          echo "Deployed to Prod"