name: Analyze Codebase

on: 
  push:
    #branches-ignore: [release*]
    branches:
      - 'feature/*'
      - 'bugfix/*'
      - 'hotfix/*'
#   pull_request:
#     branches: [master, main, 'release/*']
 
jobs:
  super-linter:
    name: Lint Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_PYTHON_BLACK: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}