name: Publish Package

on: 
  workflow_run:
    workflows: ["Build & Deploy Codebase"]
    types:
      - completed

jobs:

  publish-pre-check:
    name: Publish Pre-Check
    runs-on: ubuntu-latest
    steps:
      - name: Check if package should be published
        run: echo checking if package should be published...

  publish-package:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
        - name: Publish NPM Package
          run: echo publishing package...
        